#!/bin/bash
# postinst script for RabbitRemoteControl
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

INSTALL_ROOT=/opt/RabbitRemoteControl
USR_ROOT=/usr

case "$1" in
    configure)

        if [ ! -f $USR_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.desktop ]; then
            if [ -f $INSTALL_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.desktop ]; then
                ln -s $INSTALL_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.desktop $USR_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.desktop
                chmod a+rx $USR_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.desktop
            fi
        fi
        if [ ! -f $USR_ROOT/share/mime/packages/io.github.KangLin.RabbitRemoteControl.xml ]; then
            if [ -f $INSTALL_ROOT/share/mime/packages/io.github.KangLin.RabbitRemoteControl.xml ]; then
                if [ ! -d $USR_ROOT/share/mime/packages ]; then
                    mkdir -p $USR_ROOT/share/mime/packages
                fi
                ln -s $INSTALL_ROOT/share/mime/packages/io.github.KangLin.RabbitRemoteControl.xml $USR_ROOT/share/mime/packages/io.github.KangLin.RabbitRemoteControl.xml
            fi
        fi
        if [ ! -f $USR_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.png ]; then
            if [ -f $INSTALL_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.png ]; then
                if [ ! -d $USR_ROOT/share/pixmaps ]; then
                    mkdir -p $USR_ROOT/share/pixmaps
                fi
                ln -s $INSTALL_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.png $USR_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.png
            fi
        fi
        
        if [ ! -f $USR_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.Service.Configure.desktop ]; then
            if [ -f $INSTALL_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.Service.Configure.desktop ]; then
                ln -s $INSTALL_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.Service.Configure.desktop $USR_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.Service.Configure.desktop
            fi
        fi

        if [ ! -f $USR_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.Service.Configure.svg ]; then
            if [ -f $INSTALL_ROOT/share/icons/hicolor/scalable/apps/io.github.KangLin.RabbitRemoteControl.Service.Configure.svg ]; then
                if [ ! -d $USR_ROOT/share/pixmaps ]; then
                    mkdir -p $USR_ROOT/share/pixmaps
                fi
                ln -s $INSTALL_ROOT/share/icons/hicolor/scalable/apps/io.github.KangLin.RabbitRemoteControl.Service.Configure.svg $USR_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.Service.Configure.svg
            fi
        fi
        
        if [ ! -f $USR_ROOT/bin/rabbitremotecontrol ]; then
            ln -s $INSTALL_ROOT/bin/RabbitRemoteControlApp $USR_ROOT/bin/rabbitremotecontrol
        fi

        if [ -d $INSTALL_ROOT/etc ]; then
            chmod -R a+rw $INSTALL_ROOT/etc
        fi

        if command -v update-mime-database >/dev/null 2>&1; then
            if [ -d $USR_ROOT/share/mime ]; then
                update-mime-database $USR_ROOT/share/mime/
            fi
        fi
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database $USR_ROOT/share/applications/
        fi

        #echo "$INSTALL_ROOT/lib" > /etc/ld.so.conf.d/RabbitRemoteControl.conf
        #echo "$INSTALL_ROOT/lib/`uname -m`-linux-gnu" >> /etc/ld.so.conf.d/RabbitRemoteControl.conf
        #echo "$INSTALL_ROOT/bin" >> /etc/ld.so.conf.d/RabbitRemoteControl.conf
        #export QT_VERSION_DIR=
        #if [ -n "${QT_VERSION_DIR}" ]; then
        #    echo "/opt/qt${QT_VERSION_DIR}/lib" >> /etc/ld.so.conf.d/RabbitRemoteControl.conf
        #fi
        #ldconfig
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        #rm -fr /etc/ld.so.conf.d/RabbitRemoteControl.conf
        rm -fr $USR_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.desktop
        rm -fr $USR_ROOT/share/mime/packages/io.github.KangLin.RabbitRemoteControl.xml
        rm -fr $USR_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.png
        rm -fr $USR_ROOT/share/applications/io.github.KangLin.RabbitRemoteControl.Service.Configure.desktop
        rm -fr $USR_ROOT/share/pixmaps/io.github.KangLin.RabbitRemoteControl.Service.Configure.svg
        ldconfig
        if command -v update-mime-database >/dev/null 2>&1; then
            if [ -d $USR_ROOT/share/mime ]; then
                update-mime-database $USR_ROOT/share/mime/
            fi
        fi
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database $USR_ROOT/share/applications/
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
