# https://snapcraft.io/docs/the-snap-format
# How Snapcraft builds snaps: https://snapcraft.io/docs/how-snapcraft-builds
# Snapcraft.yaml schema: https://snapcraft.io/docs/snapcraft-yaml-schema
name: rabbitremotecontrol
version: '0.0.36'
type: app
license: GPL-3.0+
contact: kl222@126.com
donation:
  - https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png
issues: https://github.com/KangLin/RabbitRemoteControl/issues
summary: Rabbit remote control # 79 char long summary
description: |
  Rabbit remote control is  is a cross-platform,
  multi-protocol remote control software.
  .
  Allows you to use any device and system in anywhere and remotely manage
  any device and system in any way. 
  .
  It include remote desktop, remote control, remote terminal, player, network tools etc functions.
  .
  Author: Kang Lin <kl222@126.com>
  .
  Donation:
  .
  https://github.com/KangLin/RabbitCommon/raw/master/Src/Resource/image/Contribute.png
  .
  https://gitee.com/kl222/RabbitCommon/raw/master/Src/Resource/image/Contribute.png
  .
  https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png

# See: https://snapcraft.io/docs/reference-architectures
# See: https://snapcraft.io/docs/architectures
base: core24 # the base snap is the execution environment for this snap
platforms:
  amd64:
  arm64:
#base: core22
#architectures:
#  - build-on: amd64
#  - build-on: arm64

# - devel
# - stable
grade: stable # must be 'stable' to release into candidate/stable channels

# Confinement levels: https://snapcraft.io/docs/classic-confinement#heading--levels
# Classic confinement: https://snapcraft.io/docs/classic-confinement
# - devmode
# - strict
# - classic
confinement: strict # devmode # use 'strict' once you have the right plugs and slots

# lifecycle: https://snapcraft.io/docs/parts-lifecycle
# Iterating over a build: https://snapcraft.io/docs/iterating-over-a-build
# Part directives: https://snapcraft.io/docs/snapcraft-yaml-schema#part-directives
parts:
  rabbitcommon:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: dump # See: https://snapcraft.io/docs/dump-plugin
    source: https://github.com/KangLin/RabbitCommon.git
    source-type: git
    source-branch: master
    #source-depth: 1
    organize:
      '*': RabbitCommon/
    prime:
      - -*

  freerdp:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/FreeRDP/FreeRDP.git
    source-type: git
    source-tag: 3.15.0
    source-depth: 1
    build-packages:
      - libssl-dev
      - libcrypt-dev
      - libfuse3-dev
      - libpam0g-dev
      - libutf8proc-dev
      - libx11-dev
      - libxkbfile-dev
      - libusb-1.0-0-dev
      - libcjson-dev
      - libkrb5-dev
      - libicu-dev
      - libffi-dev
      # ffmpeg development headers and libraries
      - libavcodec-dev
      - libavformat-dev
      - libresample1-dev
      - libswscale-dev
      - libavutil-dev
      - libx264-dev
      - libx265-dev
      # PulseAudio client development headers and libraries
      - libpulse-dev
      - libcups2-dev # print development headers and libraries
    stage-packages:
      - libfuse3-3
      - libpam0g
      - libutf8proc3
      - libusb-1.0-0
      - libcjson1
      - libcups2t64
      - libcupsimage2t64
      - libgssapi-krb5-2
      - libgssrpc4t64
      - libkadm5clnt-mit12
      - libkadm5srv-mit12
      - libjs-jquery
      - libxkbfile1
      - libpulse0 # PulseAudio client runtime libraries
      - libffi8
      - libzvbi0t64
    cmake-parameters:
      # See: https://snapcraft.io/docs/parts-environment-variables
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_CLIENT=OFF
      - -DWITH_PLATFORM_SERVER=OFF
      - -DWITH_SHADOW=OFF
      - -DWITH_LIBSYSTEMD=off
      - -DWITH_MANPAGES=OFF
      - -DWITH_SAMPLE=OFF
      - -DWITH_CLIENT_SDL=OFF
      - -DWITH_PROXY_MODULES=OFF
      - -DCMAKE_VERBOSE_MAKEFILE=ON
    stage:
      - -usr/share
      - -usr/bin
      - -usr/sbin
      - -usr/include
      - -etc
    prime:
      - -usr/local/include
      - -usr/local/bin
      - -usr/local/lib/cmake
      - -usr/local/lib/pkgconfig
      - -usr/local/lib/*.a
      - -usr/local/lib/**/*.a

  tigervnc:
    plugin: cmake
    source: https://github.com/KangLin/tigervnc.git
    source-type: git
    source-branch: master
    source-depth: 1
    build-packages:
      - libpixman-1-dev
      - libpam0g-dev
      - libutf8proc-dev
      - libusb-1.0-0-dev
      - gettext
    stage-packages:
      - libpixman-1-0
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTS=OFF
      - -DBUILD_VIEWER=OFF
    stage:
      - -usr/share
    prime:
      - -usr/local

  pcapplusplus:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/seladb/PcapPlusPlus.git
    source-type: git
    source-tag: v24.09
    source-depth: 1
    build-packages:
      - libpcap-dev
    stage-packages:
      - libpcap0.8t64
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DPCAPPP_BUILD_EXAMPLES=OFF
      - -DPCAPPP_BUILD_TESTS=OFF
      - -DPCAPPP_BUILD_TUTORIALS=OFF
      - -DPCAPPP_INSTALL=ON
    stage:
      - -usr/share
    prime:
      - -usr/local

  # qt:
  #   plugin: nil # See: https://snapcraft.io/docs/nil-plugin
  #   build-packages:
  #     - python3-pip
  #     - python3-pip-whl
  #     - python3-pipdeptree
  #     - cpio
  #   override-pull: |
  #     echo "override-pull ......"
  #   override-build: |
  #     echo "override-build ......"
  #     cd $SNAPCRAFT_PART_INSTALL
  #     if [ ! -d qt ]; then
  #         #pip install -U pip
  #         pip install aqtinstall
  #         echo "Download qt ..."
  #         export QTVERSION=6.8.0
  #         # See: https://ddalcino.github.io/aqt-list-server/
  #         if [ "`uname -m`" == "x86_64" ]; then
  #             aqt install-qt linux desktop ${QTVERSION} linux_gcc_64 -m qt5compat qtgraphs qtimageformats qtmultimedia qtscxml qtserialport
  #             mv ${QTVERSION}/gcc_64 qt
  #         elif [ "`uname -m`" == "aarch64" ]; then
  #             aqt install-qt linux_arm64 desktop ${QTVERSION} linux_gcc_arm64 -m qt5compat qtgraphs qtimageformats qtmultimedia qtscxml qtserialport
  #             mv ${QTVERSION}/gcc_arm64 qt
  #         fi
  #     fi
  #   stage:
  #     - qt
  #   prime:
  #     - qt/lib/**/*.so*
  #     - qt/translations
  #     - qt/plugins/**/*.so*

  lxqt-build-tools:
    # See 'snapcraft plugins'
    # see: https://snapcraft.io/docs/supported-plugins
    plugin: cmake # See: https://snapcraft.io/docs/cmake-plugin
    source: https://github.com/lxqt/lxqt-build-tools.git
    source-type: git
    source-tag: 2.2.0
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr/local/
    stage:
      - -usr/local/bin

  qtermwidget:
    # See 'snapcraft plugins'
    # see: https://snapcraft.io/docs/supported-plugins
    plugin: cmake # See: https://snapcraft.io/docs/cmake-plugin
    source: https://github.com/lxqt/qtermwidget.git
    source-type: git
    source-tag: 2.2.0
    source-depth: 1
    after:
      - lxqt-build-tools
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr/local/
      - -Dlxqt2-build-tools_DIR=$CRAFT_STAGE/usr/local/share/cmake/lxqt2-build-tools
    prime:
      - -usr/local/include

  rabbitremotecontrol:
    # See 'snapcraft plugins'
    # see: https://snapcraft.io/docs/supported-plugins
    plugin: cmake # See: https://snapcraft.io/docs/cmake-plugin
    source: .
    after:
      - tigervnc
      - rabbitcommon
      - freerdp
      - pcapplusplus
      - qtermwidget
 #     - qt
    build-packages:
      - libcmark-dev
      - cmark
      - libvncserver-dev
      - libtelnet-dev
      - libpcap-dev
      - libx11-dev
      - libxcb-keysyms1-dev
      - libssh-dev
      # opengl development headers and libraries
      - libglx-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      # vulkan development headers and libraries
      - libvulkan-dev
      # openssl development headers and libraries
      - libssl-dev
      - libcrypt-dev
      # PulseAudio client development headers and libraries
      - libpulse-dev
      - libcups2-dev # print development headers and libraries
    stage-packages:
      - libcmark0.30.2
      - libvncserver1
      - libvncclient1
    cmake-parameters:
      # See: https://snapcraft.io/docs/parts-environment-variables
      - -DCMAKE_BUILD_TYPE=Release
      - -DRabbitCommon_ROOT=$CRAFT_STAGE/RabbitCommon/
      - -DCMAKE_VERBOSE_MAKEFILE=ON 
      # - -DQT_ROOT=$CRAFT_STAGE/qt
      # - -DQT_DIR=$CRAFT_STAGE/qt/lib/cmake/Qt6
      # - -DQt6_ROOT=$CRAFT_STAGE/qt
      # - -DQt6_DIR=$CRAFT_STAGE/qt/lib/cmake/Qt6
      #- -DCMAKE_MODULE_PATH=$CRAFT_STAGE/qt/lib/cmake
      #- -DCMAKE_INSTALL_PREFIX=/usr/local/
      - -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr/local/
    # build-environment:
    #   - LD_LIBRARY_PATH: "$CRAFT_STAGE/qt/lib:$LD_LIBRARY_PATH"
    #   - CMAKE_FIND_ROOT_PATH: "$CRAFT_STAGE/qt;$CRAFT_STAGE/usr/local/lib;$CMAKE_FIND_ROOT_PATH"
    #   - PATH: "$CRAFT_STAGE/qt/bin:$PATH"
    override-stage: |
      cd $CRAFT_PART_INSTALL/usr/local/bin
      # cp $SNAPCRAFT_PART_SRC/snap/local/start.sh .
      # See: https://snapcraft.io/docs/desktop-menu-support#heading--desktop-key
      sed -i 's|Icon=io\.github\.KangLin\.RabbitRemoteControl|Icon=/usr/local/share/icons/hicolor/scalable/apps/io\.github\.KangLin\.RabbitRemoteControl\.svg|' $CRAFT_PART_INSTALL/usr/local/share/applications/io.github.KangLin.RabbitRemoteControl.desktop
      sed -i 's|Path=/usr/local/bin|Path=\$\{SNAP\}/usr/local/bin|' $CRAFT_PART_INSTALL/usr/local/share/applications/io.github.KangLin.RabbitRemoteControl.desktop
      # cat > "qt.conf" << EOF
      # [Paths]
      # Prefix=../../..
      # Libraries=../../../qt/lib
      # Plugins=../../../qt/plugins
      # Translations=../../../qt/translations
      # EOF
      snapcraftctl stage
    prime:
      - -usr/bin/cmark
      - -usr/local/bin/cmark
      - -usr/local/include
      - -usr/local/lib/cmake
      - -usr/local/lib/pkgconfig
      - -usr/local/lib/*.a

apps:
 rabbitremotecontrol:
   #command: usr/local/bin/start.sh
   command: usr/local/bin/RabbitRemoteControlApp
   # See: https://snapcraft.io/docs/desktop-menu-support#heading--desktop-key
   desktop: usr/local/share/applications/io.github.KangLin.RabbitRemoteControl.desktop
   environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/local/lib::${LD_LIBRARY_PATH}
      PATH: $SNAP/usr/local/bin:$PATH
   # List extensions, run `snapcraft extensions`
   extensions:
     # [KDE neon extensions](https://documentation.ubuntu.com/snapcraft/stable/reference/extensions/kde-neon-extensions/)
     - kde-neon-6
     #- kde-neon-qt6
   # See: https://snapcraft.io/docs/supported-interfaces
   plugs:
     - network
     - network-status
     - network-control
     - network-bind
     - network-manager
     - network-manager-observe
     - network-observe
     - network-setup-control
     - network-setup-observe
     - avahi-observe
     - avahi-control
     - cifs-mount
     - nfs-mount
     - openvswitch
     - openvswitch-support
     - ppp
     - opengl
     - cups-control
     - serial-port
     - alsa
     - audio-playback
     - audio-record
     - browser-support
     - home
     - media-hub
     - mount-observe
     - optical-drive
     - password-manager-service
     - process-control
     - raw-usb
     - removable-media
     - screen-inhibit-control
     - ssh-keys
     - ssh-public-keys
     - pkcs11
     - appstream-metadata
     - hardware-observe
