# https://snapcraft.io/docs/the-snap-format
# How Snapcraft builds snaps: https://snapcraft.io/docs/how-snapcraft-builds
# Snapcraft.yaml schema: https://snapcraft.io/docs/snapcraft-yaml-schema
name: rabbitremotecontrol
base: core22 # the base snap is the execution environment for this snap
version: '0.0.27'
type: app
license: GPL-3.0+
contact: kl222@126.com
donation:
  - https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png
issues: https://github.com/KangLin/RabbitRemoteControl/issues
summary: Rabbit remote control # 79 char long summary
description: |
  Rabbit remote control is  is a cross-platform,
  multi-protocol remote control software.
  .
  Allows you to use any device and system in anywhere and remotely manage
  any device and system in any way. 
  .
  It include remote desktop, remote terminal etc remote control functions.
  .
  Author: Kang Lin <kl222@126.com>
  .
  Donation:
  .
  https://github.com/KangLin/RabbitCommon/raw/master/Src/Resource/image/Contribute.png
  .
  https://gitee.com/kl222/RabbitCommon/raw/master/Src/Resource/image/Contribute.png
  .
  https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png

grade: devel # must be 'stable' to release into candidate/stable channels
# Confinement levels: https://snapcraft.io/docs/classic-confinement#heading--levels
# Classic confinement: https://snapcraft.io/docs/classic-confinement
confinement: devmode # use 'strict' once you have the right plugs and slots

# lifecycle: https://snapcraft.io/docs/parts-lifecycle
# Iterating over a build: https://snapcraft.io/docs/iterating-over-a-build
# Part directives: https://snapcraft.io/docs/snapcraft-yaml-schema#part-directives
parts:
  rabbitcommon:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: dump # See: https://snapcraft.io/docs/dump-plugin
    source: https://github.com/KangLin/RabbitCommon.git
    source-type: git
    source-branch: master
    source-depth: 1
    organize:
      '*': RabbitCommon/
    prime:
      - -*

  freerdp:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/FreeRDP/FreeRDP.git
    source-type: git
    source-tag: 3.7.0
    source-depth: 1
    build-packages:
      - libssl-dev
      - libcrypt-dev
      - libfuse3-dev
      - libpam0g-dev
      - libutf8proc-dev
      - libusb-1.0-0-dev
      - libcjson-dev
      - libkrb5-dev
      - libicu-dev
      - libcups2-dev
      - libpkcs11-helper1-dev
      - libavcodec-dev
      - libresample1-dev
      - libswscale-dev
      - libpcap-dev
      - libcups2-dev
    stage-packages:
      - libfuse3-3
      - libpam0g
      - libutf8proc2
      - libusb-1.0-0
      - libcjson1
      - libkrb5-3
      - icu-devtools
      - libcups2
      - libcupsimage2
      - libgssapi-krb5-2
      - libgssrpc4
      - libkadm5srv-mit12
      - libkadm5clnt-mit12
      - libjs-jquery
      - libswscale5
      - x11-utils
      - libkrb5-3
      - libpkcs11-helper1
    cmake-parameters:
      # See: https://snapcraft.io/docs/parts-environment-variables
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_CLIENT=OFF
      - -DWITH_PLATFORM_SERVER=OFF
      - -DWITH_LIBSYSTEMD=off
    prime:
      - -usr/include
      - -usr/lib/cmake
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/lib/*.a
      - -usr/lib/**/*.a
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/pkgconfig

  tigervnc:
    plugin: cmake
    source: https://github.com/KangLin/tigervnc.git
    source-type: git
    source-branch: master
    source-depth: 1
    build-packages:
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - xorg-dev
      - libx11-xcb-dev
      - libx11-dev
      - libxfixes-dev
      - libxcb-randr0-dev
      - libxcb-shm0-dev
      - libxcb-xinerama0-dev
      - libxcb-composite0-dev
      - libxcomposite-dev
      - libxinerama-dev
      - libxcb1-dev
      - libx11-xcb-dev
      - libxcb-xfixes0-dev
      - libpixman-1-dev
      - libpam0g-dev
      - libutf8proc-dev
      - libusb-1.0-0-dev
      - gettext
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTS=OFF
      - -DBUILD_VIEWER=OFF
    stage:
      - usr/local/include
      - usr/local/lib
    prime:
      - -*

  rabbitremotecontrol:
    # See 'snapcraft plugins'
    # see: https://snapcraft.io/docs/supported-plugins
    plugin: cmake # See: https://snapcraft.io/docs/cmake-plugin
    source: .
    after:
      - tigervnc
      - rabbitcommon
      - freerdp
    build-packages:
      - libcmark-dev
      - cmark
      - libssl-dev
      - libcrypt-dev
      - qttools5-dev
      - qtbase5-dev
      - libqt5scxml5-dev
      - libqt5serialport5-dev
      - libqt5svg5-dev
      - qtmultimedia5-dev
      - libvncserver-dev
      - libssh-dev
      - libtelnet-dev
    stage-packages:
      - libcmark0.30.2
      - libopengl0
      - libglu1-mesa
      - libssl3
      - libcrypt1
      - libqt5scxml5
      - libqt5serialport5
      - libqt5svg5
      - libqt5xml5
      - libqt5multimedia5
      - libc6
      - libgcc-s1
      - libstdc++6
      - zlib1g
      - libssh-4
      - libvncserver1
      - libvncclient1
    cmake-parameters:
      # See: https://snapcraft.io/docs/parts-environment-variables
      - -DCMAKE_BUILD_TYPE=Release
      - -DRabbitCommon_DIR=$CRAFT_STAGE/RabbitCommon/
      - -DCMAKE_INSTALL_PREFIX=/opt/RabbitRemoteControl
      - -Dtigervnc_DIR=$CRAFT_STAGE/usr/local/lib/cmake/tigervnc
#      - -DFreeRDP-Client_DIR=$CRAFT_STAGE/usr/local/lib/cmake/FreeRDP-Client3
#      - -DFreeRDP_DIR=$CRAFT_STAGE/usr/local/lib/cmake/FreeRDP3
#      - -DWinPR_DIR=$CRAFT_STAGE/usr/local/lib/cmake/WinPR3
#      - -DFreeRDP-Shadow_DIR=$CRAFT_STAGE/usr/local/lib/cmake/FreeRDP-Shadow3
#      - -DFreeRDP-Server_DIR=$CRAFT_STAGE/usr/local/lib/cmake/FreeRDP-Server3
    override-stage: |
      cd $CRAFT_PART_INSTALL/opt/RabbitRemoteControl/bin
      if [ ! -f rabbitremotecontrol ]; then
          ln -s RabbitRemoteControlApp rabbitremotecontrol
      fi
      sed -i 's|Icon=org\.Rabbit\.RemoteControl|Icon=/opt/RabbitRemoteControl/share/pixmaps/org\.Rabbit\.RemoteControl\.svg|' $CRAFT_PART_INSTALL/opt/RabbitRemoteControl/share/applications/org.Rabbit.RemoteControl.desktop
      snapcraftctl stage
    # organize:
    #   usr/share/qt5/resources: opt/RabbitRemoteControl/bin
    #   usr/share/qt5/translations: opt/RabbitRemoteControl/bin
    prime:
      - -usr/bin/cmark
      - -opt/RabbitRemoteControl/bin/cmark
      - -opt/RabbitRemoteControl/include
      - -opt/RabbitRemoteControl/lib/cmake
      - -opt/RabbitRemoteControl/lib/pkgconfig
      - -opt/RabbitRemoteControl/lib/*.a

apps:
 rabbitremotecontrol:
   command: opt/RabbitRemoteControl/bin/RabbitRemoteControlApp
   # See: https://snapcraft.io/docs/desktop-menu-support#heading--desktop-key
   desktop: opt/RabbitRemoteControl/share/applications/org.Rabbit.RemoteControl.desktop
   environment:
     LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/opt/RabbitRemoteControl/lib/$SNAPCRAFT_ARCH_TRIPLET
     PATH: $SNAP/opt/RabbitRemoteControl/bin:$PATH
   # List extensions, run `snapcraft extensions`
   extensions:
     - kde-neon
   # See: https://snapcraft.io/docs/supported-interfaces
   plugs:
     - network
     - network-status
     - network-control
     - network-bind
     - network-manager
     - opengl
     - cups
     - cups-control
     - serial-port
     - alsa
     - audio-playback
     - audio-record
     - avahi-observe
     - browser-support
     - home
     - media-hub
     - mount-observe
     - optical-drive
     - password-manager-service
     - process-control
     - raw-usb
     - removable-media
     - screen-inhibit-control
     - ssh-keys
     - ssh-public-keys
     - unity7

