# Author: Kang Lin <kl222@126.com>

name: appimage

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_ubuntu.outputs.name }}

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build_appimage:
    strategy:
      matrix:
        BUILD_TYPE: [Release]
        qt_version: [6.9.0]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        include:
          - os: ubuntu-24.04
            qt_arch: "linux_gcc_64"
          - os: ubuntu-24.04-arm
            qt_arch: "linux_gcc_arm64"

    # See: [About GitHub-hosted runners](https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners)
    # See: [Choosing the runner for a job](https://docs.github.com/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job)
    # See: https://github.com/actions/runner-images/
    runs-on: ${{matrix.os}}

    env:
      BUILD_TYPE:  ${{matrix.BUILD_TYPE}}
      BUILD_DIR:   ${{github.workspace}}/build
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOLS_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_${{matrix.qt_arch}}_${{matrix.BUILD_TYPE}}
      RabbitRemoteControl_VERSION: v0.0.32
      artifact_name: build_appimage
      qt_modules: 'qtscxml qtmultimedia qtimageformats qtserialport qt5compat'

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Make directories
        run: |
          cmake -E make_directory ${{env.BUILD_DIR}}
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOLS_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}

      - name: Cache installed
        uses: actions/cache@v4
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
            ${{env.TOOLS_DIR}}/linuxdeploy-*
            ${{env.TOOLS_DIR}}/qt_*
          key: install_appimage

      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: |
            if [ -d RabbitCommon ]; then
                cd RabbitCommon
                git pull
            else
                git clone https://github.com/KangLin/RabbitCommon.git
            fi

      - name: Install dependency libraries
        run: |
          sudo ./Script/build_depend.sh --apt_update --base \
              --tigervnc --freerdp --pcapplusplus \
              --install ${{env.INSTALL_DIR}} \
              --source ${{env.SOURCE_DIR}} \
              --tools ${{env.TOOLS_DIR}} \
              --build ${{env.BUILD_DIR}} \
              --qt ${{matrix.qt_version}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        if: false
        with:
          dir: '${{env.TOOLS_DIR}}/qt'
          version: ${{matrix.qt_version}}
          target: 'desktop'
          arch: ${{matrix.qt_arch}}
          # See: https://ddalcino.github.io/aqt-list-server/
          modules: ${{env.qt_modules}}
          cache: true
          cache-key-prefix: cached-qt_${{matrix.qt_arch}}

      - name: build appimage
        env:
          RabbitCommon_ROOT: ${{env.SOURCE_DIR}}/RabbitCommon
          RabbitVNC_DIR: ${{ env.INSTALL_DIR }}/lib/cmake/RabbitVNC
          tigervnc_DIR: ${{env.INSTALL_DIR}}/lib/cmake/tigervnc
          # LibDataChannel_DIR: ${{ env.INSTALL_DIR }}/lib/cmake/LibDataChannel
          QtService_DIR: ${{ env.INSTALL_DIR }}/lib/cmake/QtService
          FreeRDP_DIR: ${{ env.INSTALL_DIR }}/lib/cmake/FreeRDP3
          WinPR_DIR: ${{ env.INSTALL_DIR }}/lib/cmake/WinPR3
          FreeRDP-Client_DIR: ${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Client3
          FreeRDP-Shadow_DIR: ${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Shadow3
          FreeRDP-Server_DIR: ${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Server3
          BUILD_FREERDP: ON
          PcapPlusPlus_DIR: ${{env.INSTALL_DIR}}/lib/cmake/pcapplusplus
        run: |
          export QT_ROOT=${{env.TOOLS_DIR}}/qt_`uname -m`
          export Qt6_DIR=$QT_ROOT
          export QMAKE=$QT_ROOT/bin/qmake
          export PKG_CONFIG_PATH=$QT_ROOT/lib/pkgconfig:${{env.INSTALL_DIR}}/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=$QT_ROOT/lib:${{env.INSTALL_DIR}}/lib:$LD_LIBRARY_PATH
          export QT_PLUGIN_PATH=$QT_ROOT/plugins
          export CMAKE_PREFIX_PATH=$QT_ROOT
          #export QMAKE=$Qt6_DIR/bin/qmake6
          ${{github.workspace}}/Script/build_appimage.sh
          md5sum RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_`uname -m`.AppImage > RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_`uname -m`.AppImage.md5sum

      - name: update configure file
        if: ${{ matrix.BUILD_TYPE == 'Release'}}
        #continue-on-error: true
        run: |
          sudo Xvfb :91.0 -ac -screen 0 1200x900x24 &
          export DISPLAY=:91.0
          echo "Update update_linux.json ......"
          export QT_XCB_GL_INTEGRATION=none
          #export QT_DEBUG_PLUGINS=1
          ARCH=`uname -m`
          MD5SUM=`cat RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_$ARCH.AppImage.md5sum|awk '{print $1}'`
          echo "MD5SUM RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_$ARCH.AppImage: ${MD5SUM}"
          echo "Generate update configure file ......"
          ./RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_$ARCH.AppImage \
            -f "${{github.workspace}}/update_appimage_${{matrix.qt_arch}}_qt${{matrix.qt_version}}.json" \
            --foc 1 \
            --file-name RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_$ARCH.AppImage \
            -u "https://github.com/KangLin/RabbitRemoteControl/releases/download/${{env.RabbitRemoteControl_VERSION}}/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_${ARCH}.AppImage;https://sourceforge.net/projects/rabbitremotecontrol/files/${{env.RabbitRemoteControl_VERSION}}/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_Linux_${ARCH}.AppImage" \
            --md5 "${MD5SUM}"

      - name: Update artifact
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}_${{matrix.os}}
          path: |
            ${{github.workspace}}/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_*.AppImage
            ${{github.workspace}}/update_appimage_${{matrix.qt_arch}}_qt${{matrix.qt_version}}.json
