name: build

env:
  artifact_path: artifact_path
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
  pull_request:
  
jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml

  msvc:
    uses: ./.github/workflows/msvc.yml

  mingw:
    uses: ./.github/workflows/mingw.yml

  macos:
    uses: ./.github/workflows/macos.yml

  android:
    uses: ./.github/workflows/android.yml
  
  deploy:
    #if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [ubuntu, mingw, msvc, android, macos]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Download ubuntu
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.ubuntu.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download msvc
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.msvc.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download mingw
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.mingw.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download macos
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.macos.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download android
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.android.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Make note file
        run: |
          echo "[:cn: 修改日志](https://github.com/KangLin/RabbitRemoteControl/blob/${{env.RabbitRemoteControl_VERSION}}/ChangeLog_zh_CN.md)" > Release.md
          echo "[:en: Change log](https://github.com/KangLin/RabbitRemoteControl/blob/${{env.RabbitRemoteControl_VERSION}}/ChangeLog.md)" >> Release.md
          echo "" >> Release.md
          echo "文件签名:" >> Release.md
          cd ${{ env.artifact_path }}
          for file in *
          do
              echo $file
              if [ -f $file ]; then
                  md5sum $file > $file.md5sum
                  cat $file.md5sum >> ${{github.workspace}}/Release.md
              fi
          done

      - name: Upload To Github Release
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-file ${{github.workspace}}/Release.md
          gh release upload ${{ github.ref_name }} ${{github.workspace}}/${{ env.artifact_path }}/* ${{github.workspace}}/Release.md
