name: CMake github bash script

on: [push]
  
jobs:
  use_install_qt:
    name: use install qt
  
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] #macos-latest, 
        BUILD_TYPE: [Release, Debug]
    runs-on: ${{ matrix.os }}

    env:
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
  
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Qt
      # You may pin to the exact commit or the version.
      # uses: jurplel/install-qt-action@a962fb91949c8e846a3e4a944d50e7ef5cc3a28a
      uses: jurplel/install-qt-action@v2.11.1
      with:
        # Directory to install Qt
        dir: ${{runner.workspace}}/qt # optional
        # Version of Qt to install
        version: 5.12.9 # optional, default is 5.15.2
        # Host platform
        #host: linux # optional
        # Target platform for build
        target: desktop # optional, default is desktop
        # Architecture for Windows/Android
        #arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: true # optional, default is true
        # Additional Qt modules to install
        modules: none # optional
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: false # optional, default is false
        # Whether or not to automatically run setup-python to find a valid python version.
        setup-python: false # optional, default is true
        # Qt tools to download--specify comma-separated argument lists which are themselves separated by spaces: <tool_name>,<tool_version>,<tool_arch>
        #tools: # optional
        # Whether or not to actually install Qt or just the tools from the tools argument
        tools-only: false # optional, default is false
        # Version of aqtinstall to use in case of issues
        #aqtversion: # optional, default is ==0.10.0
        # Version of py7zr to use in case of issues
        #py7zrversion: # optional, default is ==0.11.0
        # Any extra arguments to append to the back
        #extra: # optional

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./ci/build_github_action.sh #${{github.workspace}} ${{runner.workspace}}/Tools ${{runner.workspace}}/ThirdLibs ${{runner.workspace}}/ThirdLibsSrc
