name: CMake mingw

on: [push]

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [windows-latest]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        BUILD_TYPE: [Release, Debug]

    defaults:
      run:
        shell: cmd
        
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/source
      TOOSL_DIR:   ${{github.workspace}}/tools
      INSTALL_DIR: ${{github.workspace}}/install

    steps:
    - uses: actions/checkout@v2
      #with:
        #fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        path-type: strict
        shell: msys2 {0}
        install: >-
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-nsis
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-libvncserver
            mingw-w64-x86_64-cyrus-sasl
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-openjpeg 
            
    - name: make_directory
      run: |
        cmake -E make_directory ${{env.SOURCE_DIR}}
        cmake -E make_directory ${{env.TOOSL_DIR}}
        cmake -E make_directory ${{env.INSTALL_DIR}}
        
    - name: git clone RabbitCommon
      working-directory: ${{env.SOURCE_DIR}}
      run: git clone https://github.com/KangLin/RabbitCommon.git
    
    - name: build tigervnc
      working-directory: ${{env.SOURCE_DIR}}
      run: |
        git clone https://github.com/KangLin/tigervnc.git 
        cd ${{env.SOURCE_DIR}}/tigervnc
        cmake -E make_directory build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DBUILD_TESTS=OFF -DBUILD_VIEWER=OFF
        cmake --build . --config ${{ matrix.BUILD_TYPE }}
        cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
          
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: build RabbitRemoteControl
      env:
        RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        Qt5_Dir: C:\msys64\mingw64
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/install -Dtigervnc_DIR=${{ github.workspace }}/build/install/lib/cmake  -DCMAKE_PREFIX_PATH=${{ env.INSTALL_DIR }}
        cmake --build . --config ${{ matrix.BUILD_TYPE }}
        cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
