name: CMake ubuntu

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    strategy:
      matrix:
        os: [Ubuntu-20.04, Ubuntu-18.04]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        BUILD_TYPE: [Release, Debug]

    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: git describe --tags
    
    - name: git clone RabbitCommon
      working-directory: ${{runner.workspace}}
      run: git clone https://github.com/KangLin/RabbitCommon.git
      
    - name: apt helper action
      uses: ryankurte/action-apt@v0.2.0
      with:
        # architectures to pass to dpkg --add-architecture
        #architectures: # optional
        # apt packages to install
        packages: freerdp2-dev libvncserver-dev libssh-dev liblog4cplus-dev debhelper fakeroot qttools5-dev qttools5-dev-tools qtbase5-dev qtbase5-dev-tools qtmultimedia5-dev qtlocation5-dev libqt5svg5-dev

    - name: build_debpackage.sh
      run: ./build_debpackage.sh /usr/lib/`uname -m`-linux-gnu/qt5
      env:
        RabbitCommon_DIR: ${{runner.workspace}}/RabbitCommon
    
    - name: copy deb file
      run: cp ../rabbitremotecontrol_*.deb .
      
    - name: update 
      uses: actions/upload-artifact@v2
      with:
          name: rabbitremotecontrol_${{ matrix.os }}
          path: rabbitremotecontrol_*.deb

    #- name: Release
    #  uses: fnkr/github-action-ghr@v1
    #  if: startsWith(github.ref, 'refs/tags/')
    #  env:
    #    GHR_COMPRESS: xz
    #    GHR_PATH: ${{github.workspace}}/rabbitremotecontrol_*.deb
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload To Github Release
      # You may pin to the exact commit or the version.
      # uses: xresloader/upload-to-github-release@3ad14478ee4fb9bd65e84c6d496a7d6862892f43
      uses: xresloader/upload-to-github-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
        file: ${{github.workspace}}/rabbitremotecontrol_*.deb # default is 
        # The files or file patterns to delete before uploading new files. You can delete multiple files by split them by semicolon. You can use the glob pattern to find the files.
        #delete_file: # optional, default is 
        # If you need to overwrite existing files, add overwrite: true to the with.
        #overwrite: # optional, default is false
        # The resultant deployment is a draft Release that only repository collaborators can see. This gives you an opportunity to examine and edit the draft release.
        draft: true # optional, default is true
        # The resultant deployment is a Prerelease. This gives you an opportunity to examine and edit the prerelease.
        prerelease: true # optional, default is false
        # With tags: true, your Releases deployment will trigger if and only if the build is a tagged build.
        tags: true # optional, default is false
        # Only work on these branches(splited by semicolon), set to nothing to accept all branches.
        branches: master # optional, default is 
        # With verbose: true, be verbose.
        verbose: true # optional, default is false
        # Set custom tag name.
        tag_name: v0.0.1 # optional, default is 
        # If try to update latest release.
        update_latest_release: true # optional, default is false
    
#  build_script:
#    strategy:
#      matrix:
#        os: [Ubuntu-20.04, Ubuntu-18.04]
 
#    runs-on: ${{ matrix.os }}

#    steps:
#    - uses: actions/checkout@v2

#    - name: script
#      run: |
#        /bin/bash ./ci/build-install-tools.sh
#        /bin/bash ./ci/build.sh
#      env:
#        BUILD_TARGERT: "unix"
#        DOWNLOAD_QT: "APT"
#        GENERATORS: "Unix Makefiles"
