name: macos

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_macos.outputs.name }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_macos:
    strategy:
      matrix:
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        BUILD_TYPE: [Release, Debug]
        qt_version: [6.8.1, 5.15.2, 5.12.12]
        qt_arch: [clang_64]
        VCPKG_TARGET_TRIPLET: [x64-osx]
        include:
          - qt_version: 6.8.1
            qt_modules: qtscxml qtmultimedia qtserialport qt5compat

          - qt_version: 5.15.2

          - qt_version: 5.12.12

    # See: https://docs.github.com/zh/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    # See: https://github.com/actions/runner-images/tree/main
    runs-on: macos-13

    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOSL_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install
      qt_modules: ${{matrix.qt_modules}}
      VCPKGGITCOMMITID: 9f5925e81bbcd9c8c34cc7a8bd25e3c557b582b2
      VCPKG_TARGET_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}
      VCPKG_DEFAULT_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}
      VCPKG_MANIFEST_FEATURES: "freerdp;vnc;wol"
      artifact_name: build_macos
      RabbitRemoteControl_VERSION: v0.0.29

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
    
      - name: Make directories
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOSL_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}

      - name: Cache installed
        uses: actions/cache@v3
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key: install_macos_qt${{matrix.qt_version}}_${{matrix.qt_arch}}_${{matrix.BUILD_TYPE}}

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{env.VCPKGGITCOMMITID}}
          vcpkgDirectory: ${{env.SOURCE_DIR}}/vcpkg          

      - name: install nasm
        run: |
          brew install nasm

#      - name: build FreeRDP
#        working-directory: ${{env.SOURCE_DIR}}
#        run: |
#          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/FreeRDP3 ]; then
#            git clone https://github.com/FreeRDP/FreeRDP.git
#            # git clone https://github.com/KangLin/FreeRDP.git
#            cd FreeRDP
#            git checkout -b 04fa5b3033722df4fba45c02056be8e7cb45d7c6 04fa5b3033722df4fba45c02056be8e7cb45d7c6
#            git submodule update --init --recursive
#            cmake -E make_directory build
#            cd build
#            cmake .. \
#                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
#                -DCMAKE_INSTALL_PREFIX="${{env.INSTALL_DIR}}" \
#                -DWITH_SERVER=ON \
#                -DWITH_CLIENT_SDL=OFF \
#                -DWITH_KRB5=OFF \
#                -DWITH_MANPAGES=OFF \
#                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake"
#            cmake --build . --config ${{matrix.BUILD_TYPE}} --parallel $(nproc)
#            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
#          fi

      - name: build RabbitVNC
        if: false
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/RabbitVNC ]; then
            git clone --depth=1 https://github.com/KangLin/RabbitVNC.git
            cd ${{env.SOURCE_DIR}}/RabbitVNC
            cmake -E make_directory build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
                -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} \
                -DBUILD_TESTS=OFF -DBUILD_VIEWER=OFF \
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/RabbitVNC/vcpkg_installed \
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
                -DVCPKG_VERBOSE=ON \
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}}
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --parallel $(nproc)
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
          fi

      - name: build tigervnc
        #if: false #${{ matrix.BUILD_TYPE == 'Debug' }}
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/tigervnc ]; then
            git clone --depth=1 https://github.com/KangLin/tigervnc.git
            cd ${{env.SOURCE_DIR}}/tigervnc
            cmake -E make_directory build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
                -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} \
                -DBUILD_TESTS=OFF -DBUILD_VIEWER=OFF \
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/tigervnc/vcpkg_installed \
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
                -DVCPKG_VERBOSE=ON \
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}}               
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --parallel $(nproc)
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
          fi

      - name: Build libvncserver
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/LibVNCServer ]; then
            git clone --depth=1 https://github.com/KangLin/libvncserver.git
            #git clone https://github.com/LibVNC/libvncserver.git
            cd libvncserver
            #git checkout -b 5deb43e2837e05e5e24bd2bfb458ae6ba930bdaa 5deb43e2837e05e5e24bd2bfb458ae6ba930bdaa
            cmake -E make_directory build
            cd build
            cmake .. \
                -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
                -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} \
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/libvncserver/vcpkg_installed \
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
                -DVCPKG_VERBOSE=ON \
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} \
                -DWITH_OPENSSL=ON \
                -DWITH_GCRYPT=OFF \
                -DWITH_EXAMPLES=OFF \
                -DWITH_TESTS=OFF
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --parallel $(nproc)
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
          fi

#      - name: build libdatachannel
#        working-directory: ${{env.SOURCE_DIR}}
#        run: |
#          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/LibDataChannel ]; then
#            git clone -b v0.22.2 --depth=1 https://github.com/paullouisageneau/libdatachannel.git
#            cd libdatachannel
#            git submodule update --init --recursive
#            cmake -E make_directory build
#            cd build
#            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
#                -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} \
#                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
#                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/libdatachannel/vcpkg_installed \
#                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
#                -DVCPKG_VERBOSE=ON \
#                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}}
#            cmake --build . --config ${{ matrix.BUILD_TYPE }}
#            cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
#          fi

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: '${{env.TOOSL_DIR}}/qt' # optional
          version: '${{matrix.qt_version}}' # optional, default is 5.15.2
          arch: '${{matrix.qt_arch}}' # optional
          modules: '${{env.qt_modules}}' # optional
          cache: true
          cache-key-prefix: cached_qt

      - name: build qxmpp
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/qxmpp ]; then
            git clone -b v1.4.0 "https://github.com/qxmpp-project/qxmpp.git"
            cd qxmpp
            cmake -E make_directory build
            cd build
            cmake .. \
                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
                -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF \
                -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_DIR}} \
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/qxmpp/vcpkg_installed \
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
                -DVCPKG_VERBOSE=ON \
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}}                
            cmake --build . --config ${{matrix.BUILD_TYPE}} --parallel $(nproc)
            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
          fi

      - name: build QtService
        working-directory: ${{env.SOURCE_DIR}}
        env:
          QT_ROOT: /usr/lib/`uname -m`-linux-gnu/qt5
        run: |
          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/QtService ]; then
            git clone --depth=1 https://github.com/KangLin/qt-solutions.git
            cd qt-solutions/qtservice
            git submodule update --init --recursive
            cmake -E make_directory build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
                -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} \
                -DQT_DIR=${{env.QT_ROOT}}/lib/cmake/Qt5 \
                -DQt5_DIR=${{env.QT_ROOT}}/lib/cmake/Qt5 \
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/QtService/vcpkg_installed \
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
                -DVCPKG_VERBOSE=ON \
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}}                
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --parallel $(nproc)
            cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
          fi

      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: git clone https://github.com/KangLin/RabbitCommon.git

      - name: Build RabbitRemoteControl
        working-directory: ${{github.workspace}}/build
        env:
          RabbitCommon_ROOT: ${{env.SOURCE_DIR}}/RabbitCommon
        run: |
          if [ "${{ matrix.BUILD_TYPE }}" == "Release" ]; then
              export BUILD_SERVICE=OFF
          else
              export BUILD_SERVICE=ON
          fi
          cmake ${{github.workspace}} \
              -DCMARK_SHARED=OFF \
              -DCMARK_TESTS=OFF \
              -DCMARK_STATIC=ON \
              -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
              -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/install \
              -DCMAKE_PREFIX_PATH=${{env.INSTALL_DIR}}/lib/cmake \
              -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
              -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
              -DVCPKG_VERBOSE=ON \
              -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} \
              -DBUILD_FREERDP=ON \
              -DLibVNCServer_DIR="${{env.INSTALL_DIR}}/lib/cmake/LibVNCServer" \
              -DRabbitVNC_DIR=${{env.INSTALL_DIR}}/lib/cmake/RabbitVNC \
              -Dtigervnc_DIR=${{env.INSTALL_DIR}}/lib/cmake/tigervnc \
              -DQXmpp_DIR=${{env.INSTALL_DIR}}/lib/cmake/qxmpp \
              -DQtService_DIR=${{env.INSTALL_DIR}}/lib/cmake/QtService \
              -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake \
              -DFreeRDP_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP2 \
              -DFreeRDP-Client_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Client2 \
              -DWinPR_DIR=${{env.INSTALL_DIR}}/lib/cmake/WinPR2 \
              -DFreeRDP-Shadow_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Shadow2 \
              -DFreeRDP-Server_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Server2
          cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install --parallel $(nproc)
          7z a RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_macos.zip ./install/*

      - name: Update configure file
        if: ${{ matrix.BUILD_TYPE == 'Release' && matrix.qt_version == '6.8.1' }}
        working-directory: ${{github.workspace}}/build
        run: |
          ${{env.SOURCE_DIR}}/RabbitCommon/Install/GenerateJsonFile.sh \
               "${{github.workspace}}/build/update_macos_${{matrix.qt_version}}.json" \
               RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_macos.zip \
               macos ${{matrix.config_arch}} \
               "https://github.com/KangLin/RabbitRemoteControl/releases/download/v${{env.RabbitRemoteControl_VERSION}}/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_macos.zip;https://sourceforge.net/projects/rabbitRabbitRemoteControl/files/v${{env.RabbitRemoteControl_VERSION}}/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_macos.zip"

      - name: Update artifact
        if: ${{ matrix.BUILD_TYPE == 'Release' && matrix.qt_version == '6.8.1' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}_${{matrix.qt_version}}_${{matrix.qt_arch}}
          path: |
            ${{github.workspace}}/build/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_macos.zip
            ${{github.workspace}}/build/update_macos_${{matrix.qt_version}}.json
