name: msvc

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_msvc.outputs.name }}

jobs:
  build_msvc:

    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]
        qt_version: [6.6.2, 5.15.2, 5.12.12]
        include:
          - qt_version: 6.6.2
            qt_arch: win64_msvc2019_64
            qt_modules: qtscxml qtmultimedia qtimageformats qtwebchannel qtwebsockets qtwebview qtpositioning qtserialport
            CMAKE_GENERATOR_PLATFORM: x64
            VCPKG_TARGET_TRIPLET: x64-windows
            VCPKG_PLATFORM_TOOLSET: v142
            
          - qt_version: 5.15.2
            qt_arch: win64_msvc2019_64
            CMAKE_GENERATOR_PLATFORM: x64
            VCPKG_TARGET_TRIPLET: x64-windows
            VCPKG_PLATFORM_TOOLSET: v142

          - qt_version: 5.12.12
            qt_arch: win32_msvc2017
            CMAKE_GENERATOR_PLATFORM: Win32
            VCPKG_TARGET_TRIPLET: x86-windows
            VCPKG_PLATFORM_TOOLSET: v141

    runs-on: windows-latest

    env:
      SOURCE_DIR:  ${{github.workspace}}\.cache\source
      TOOSL_DIR:   ${{github.workspace}}\.cache\tools
      INSTALL_DIR: ${{github.workspace}}\.cache\install
      VCPKGGITCOMMITID: 3f966cf6a8654a0bc067738bcb95d489e197ad68
      VCPKG_TARGET_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}
      VCPKG_DEFAULT_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}
      VCPKG_PLATFORM_TOOLSET: ${{matrix.VCPKG_PLATFORM_TOOLSET}}
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      CMAKE_GENERATOR_PLATFORM: ${{matrix.CMAKE_GENERATOR_PLATFORM}}
      qt_modules: qtwebengine ${{matrix.qt_modules}}
      artifact_name: build_msvc
      RabbitRemoteControl_VERSION: v0.0.26

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Make directories
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOSL_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          
      - name: Cache installed
        uses: actions/cache@v3
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key: install_msvc_qt${{matrix.qt_version}}_${{matrix.qt_arch}}_${{matrix.BUILD_TYPE}}_2024_03_01

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{env.VCPKGGITCOMMITID}}
          vcpkgDirectory: ${{env.SOURCE_DIR}}/vcpkg

      - name: run vcpkg
        if: false
        working-directory: ${{github.workspace}}
        run: |
          vcpkg install --triplet ${{matrix.VCPKG_TARGET_TRIPLET}} --x-feature=vnc

#    - name: build libdatachannel
#      working-directory: ${{env.SOURCE_DIR}}
#      run: |
#        IF NOT EXIST ${{env.INSTALL_DIR}}\lib\cmake\LibDataChannel (
#          git clone -b v0.15.5 https://github.com/paullouisageneau/libdatachannel.git
#          cd libdatachannel
#          git submodule update --init --recursive
#          cmake -E make_directory build
#          cd build
#          cmake .. ^
#            -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
#            -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
#            -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
#            -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} ^
#            -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake"
#          cmake --build . --config ${{matrix.BUILD_TYPE}}
#          cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
#        )

#      - name: Build FreeRDP
#        working-directory: ${{env.SOURCE_DIR}}
#        run: |
#          IF NOT EXIST ${{env.INSTALL_DIR}}\lib\cmake\FreeRDP3 (
#            git clone https://github.com/FreeRDP/FreeRDP.git
#            ; git clone https://github.com/KangLin/FreeRDP.git
#            cd FreeRDP
#            git checkout -b 04fa5b3033722df4fba45c02056be8e7cb45d7c6 04fa5b3033722df4fba45c02056be8e7cb45d7c6
#            git submodule update --init --recursive
#            cmake -E make_directory build
#            cd build
#            cmake .. ^
#                -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
#                -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
#                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
#                -DCMAKE_INSTALL_PREFIX="${{env.INSTALL_DIR}}" ^
#                -DWITH_SERVER=ON ^
#                -DWITH_CLIENT_SDL=OFF ^
#                -DWITH_KRB5=OFF ^
#                -DWITH_MANPAGES=OFF ^
#                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake"
#            cmake --build . --config ${{matrix.BUILD_TYPE}}
#            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
#          )

      - name: build RabbitVNC
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          IF NOT EXIST ${{env.INSTALL_DIR}}\lib\cmake\RabbitVNC (
            git clone https://github.com/KangLin/RabbitVNC.git 
            cd RabbitVNC
            cmake -E make_directory build
            cd build
            cmake .. ^
                -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
                -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
                -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}" ^
                -DBUILD_TESTS=OFF -DBUILD_VIEWER=OFF ^
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" ^
                -DVCPKG_VERBOSE=ON ^
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/RabbitVNC/vcpkg_installed ^
                -DVCPKG_TRACE_FIND_PACKAGE=ON ^
                -DBUILD_VIEWER=OFF ^
                -DBUILD_TESTS=OFF
            cmake --build . --config ${{matrix.BUILD_TYPE}}
            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
          )

      - name: build tigervnc
        if: false # ${{ matrix.BUILD_TYPE == 'Debug'}}
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          IF NOT EXIST ${{env.INSTALL_DIR}}\lib\cmake\tigervnc (
            git clone https://github.com/KangLin/tigervnc.git 
            cd tigervnc
            cmake -E make_directory build
            cd build
            cmake .. ^
                -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
                -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
                -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}" ^
                -DBUILD_TESTS=OFF -DBUILD_VIEWER=OFF ^
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" ^
                -DVCPKG_VERBOSE=ON ^
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/tigervnc/vcpkg_installed ^
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
                -DVCPKG_TRACE_FIND_PACKAGE=ON ^
                -DBUILD_VIEWER=OFF ^
                -DBUILD_TESTS=OFF
            cmake --build . --config ${{matrix.BUILD_TYPE}}
            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
          )

      - name: Build libvncserver
        if: ${{ matrix.BUILD_TYPE == 'Debug'}}
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          IF NOT EXIST ${{env.INSTALL_DIR}}\lib\cmake\LibVNCServer (
            #git clone https://github.com/KangLin/libvncserver.git
            git clone https://github.com/LibVNC/libvncserver.git
            cd libvncserver
            ;git checkout -b 5deb43e2837e05e5e24bd2bfb458ae6ba930bdaa 5deb43e2837e05e5e24bd2bfb458ae6ba930bdaa
            cmake -E make_directory build
            cd build
            cmake .. ^
                -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
                -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
                -DWITH_OPENSSL=ON -DWITH_GCRYPT=OFF -DBUILD_TESTS=OFF ^
                -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}" ^
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" ^
                -DVCPKG_VERBOSE=ON ^
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/libvncserver/vcpkg_installed ^
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
                -DVCPKG_TRACE_FIND_PACKAGE=ON ^
                -DWITH_EXAMPLES=OFF ^
                -DWITH_TESTS=OFF
            cmake --build . --config ${{matrix.BUILD_TYPE}}
            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
          )
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: '${{env.TOOSL_DIR}}/qt' # optional
          version: '${{matrix.qt_version}}' # optional, default is 5.15.2
          arch: '${{matrix.qt_arch}}' # optional
          modules: '${{env.qt_modules}}' # optional.  see: https://ddalcino.github.io/aqt-list-server/
          cache: true
          cache-key-prefix: cached-qt

      - name: build qxmpp
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          IF NOT EXIST ${{env.INSTALL_DIR}}\lib\cmake\qxmpp (
            git clone -b v1.4.0 "https://github.com/qxmpp-project/qxmpp.git"
            cd qxmpp
            cmake -E make_directory build
            cd build
            cmake .. ^
                -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
                -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
                -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF ^
                -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_DIR}} ^
                -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake ^
                -DVCPKG_VERBOSE=ON ^
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/qxmpp/vcpkg_installed ^
                -DVCPKG_TRACE_FIND_PACKAGE=ON 
            cmake --build . --config ${{matrix.BUILD_TYPE}}
            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
          )

      - name: build QtService
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          IF NOT EXIST ${{env.INSTALL_DIR}}\lib\cmake\QtService (
            git clone "https://github.com/KangLin/qt-solutions.git"
            cd qt-solutions/qtservice
            cmake -E make_directory build
            cd build
            cmake .. ^
                -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
                -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
                -DBUILD_EXAMPLES=OFF ^
                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
                -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_DIR}} ^
                -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake ^
                -DVCPKG_VERBOSE=ON ^
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
                -DVCPKG_TRACE_FIND_PACKAGE=ON
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/QtService/vcpkg_installed
            cmake --build . --config ${{matrix.BUILD_TYPE}}
            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install
          )

      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: git clone https://github.com/KangLin/RabbitCommon.git

      - name: Build RabbitRemoteControl
        working-directory: ${{github.workspace}}\build
        env:
          RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        run: |
          IF /i "${{matrix.BUILD_TYPE}}" == "Release" (
              echo "Build Release ......"
              set BUILD_RABBITVNC=ON
              set BUILD_LibVNCServer=OFF
              set BUILD_TigerVNC=OFF
              set BUILD_SERVICE=OFF
          ) else (
              echo "Build Debug ......"
              set BUILD_LibVNCServer=ON
              set BUILD_TigerVNC=ON
              set BUILD_SERVICE=ON
          )
          cd ${{github.workspace}}/build
          cmake ${{github.workspace}} ^
            -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
            -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
            -DCMARK_SHARED=OFF ^
            -DCMARK_TESTS=OFF ^
            -DCMARK_STATIC=ON ^
            -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
            -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install ^
            -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake ^
            -DVCPKG_VERBOSE=ON ^
            -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
            -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
            -DVCPKG_TRACE_FIND_PACKAGE=ON ^
            -DBUILD_QUIWidget=OFF ^
            -DBUILD_APP=ON ^
            -DLibVNCServer_DIR="${{env.INSTALL_DIR}}/lib/cmake/LibVNCServer" ^
            -DRabbitVNC_DIR=${{env.INSTALL_DIR}}/lib/cmake/RabbitVNC ^
            -Dtigervnc_DIR=${{env.INSTALL_DIR}}/lib/cmake/tigervnc ^
            -DQXmpp_DIR=${{env.INSTALL_DIR}}/lib/cmake/qxmpp ^
            -DQtService_DIR=${{env.INSTALL_DIR}}/lib/cmake/QtService ^
            -DBUILD_FREERDP=ON ^
            -DFreeRDP_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP2 ^
            -DFreeRDP-Client_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Client2 ^
            -DWinPR_DIR=${{env.INSTALL_DIR}}/lib/cmake/WinPR2 ^
            -DFreeRDP-Shadow_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Shadow2 ^
            -DFreeRDP-Server_DIR=${{env.INSTALL_DIR}}/lib/cmake/FreeRDP-Server2
          cmake --build . --config ${{matrix.BUILD_TYPE}}
          IF "${{matrix.BUILD_TYPE}}" == "Release" (
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: DependLibraries"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component DependLibraries --strip
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Runtime"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Runtime --strip
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Application"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Application --strip
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Plugin"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Plugin --strip
          ) else (
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Runtime Application Plugin"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Runtime
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Application
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Plugin
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component DependLibraries
          )

      - name: Package
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        working-directory: ${{github.workspace}}\build
        run: |
          copy /Y ${{env.INSTALL_DIR}}\bin\*.dll install\
          7z a RabbitRemoteControl_windows_${{env.RabbitRemoteControl_VERSION}}.zip .\install\*
          makensis Install.nsi
          copy /Y RabbitRemoteControl_Setup_${{env.RabbitRemoteControl_VERSION}}.exe RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_Setup.exe

      - name: Update configure file
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        working-directory: ${{github.workspace}}\build
        run: |
          install\bin\RabbitRemoteControlApp.exe ^
                -f "update_${{matrix.qt_arch}}_qt${{matrix.qt_version}}.json" ^
                --foc 1 ^
                -u https://github.com/KangLin/RabbitRemoteControl/releases/download/${{env.RabbitRemoteControl_VERSION}}/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_Setup.exe;https://sourceforge.net/projects/rabbitremotecontrol/files/${{env.RabbitRemoteControl_VERSION}}/RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_Setup.exe ^
                --pf RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_Setup.exe ^
                -m "${{env.RabbitRemoteControl_VERSION}}"
          RENAME update_${{matrix.qt_arch}}_qt${{matrix.qt_version}}.json.xml update_windows.xml
      
      - name: Update artifact
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}\build\RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_Setup.exe
            ${{github.workspace}}\build\update_${{matrix.qt_arch}}_qt${{matrix.qt_version}}.json

      - name: Update artifact update_windows.xml
        if: ${{ matrix.BUILD_TYPE == 'Release'}}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}\build\update_windows.xml
            

#    - name: Upload To Github Release
#      if: ${{ matrix.BUILD_TYPE == 'Release' && '5.12.12' == matrix.qt_version && startsWith(github.ref, 'refs/tags/') }}
#      uses: softprops/action-gh-release@v0.1.14
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        prerelease: true
##        body: |
##          [:cn: 修改日志](ChangeLog_zh_CN.md) [:cn: 说明](README_zh_CN.md)
##          [:us: Change log](ChangeLog.md) [:us: README](README.md)
#        files: |
#          ${{github.workspace}}\build\RabbitRemoteControl_windows_${{env.RabbitRemoteControl_VERSION}}.zip
#          ${{github.workspace}}\build\RabbitRemoteControl_windows_${{env.RabbitRemoteControl_VERSION}}.zip.md5sum
#          ${{github.workspace}}\build\RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_qt_${{matrix.qt_version}}_Setup.exe
#          ${{github.workspace}}\build\RabbitRemoteControl_${{env.RabbitRemoteControl_VERSION}}_qt_${{matrix.qt_version}}_Setup.exe.md5sum
#          ${{github.workspace}}\build\update_windows.xml
