# Author: Kang Lin <kl222@126.com>

name: snap

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_snap.outputs.name }}

jobs:
  build_snap:
    env:
      artifact_name: build_snap
      RabbitRemoteControl_VERSION: v0.0.36

    # See: [About GitHub-hosted runners](https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners)
    # See: [Choosing the runner for a job](https://docs.github.com/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job)
    # See: https://github.com/actions/runner-images/
    runs-on: ubuntu-latest

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # You can now run Snapcraft shell commands
      - name: Build snap
        run: |
           sudo snap install snapcraft --classic
           sudo usermod -aG lxd $USER
           snapcraft -v --debug

      - name: Update artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}/*.snap
