name: mirror sourceforge
on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: mirror
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: ssh://kl222@git.code.sf.net/p/rabbitremotecontrol/code
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          GIT_PUSH_ARGS: --force
